import { useEffect, useMemo, useRef, useState } from 'react';
import type { ApiAxie } from '@/game/axie-roster';
import { createHexGridSlots } from '@/game/hex-grid';
import type { BattleBoardAssignment, BattleBoardLayout } from '@/game/battle-board-scene';
import type { BattleRangeSettings } from '@/game/battle-range';
import { createSandboxBattle, SANDBOX_AXIE_STATS, SANDBOX_BATTLE_STEP, SANDBOX_CHIMERA_STATS, SandboxBattle, stepSandboxBattle } from '@/game/sandbox-battle';

type Props = { layout: BattleBoardLayout; range: BattleRangeSettings; activeAxies: readonly ApiAxie[]; onSaveLayout: (layout: BattleBoardLayout) => void; onSaveRange: (range: BattleRangeSettings) => void; onClose: () => void };
type DraftAssignment = { slotId: string; side: 'player' | 'enemy'; axieId?: string; mob?: 'chimera-pack' };

export default function BattleSandbox({ layout, range, activeAxies, onSaveLayout, onSaveRange, onClose }: Props) {
  const canvas = useRef<HTMLCanvasElement>(null), dialog = useRef<HTMLDialogElement>(null);
  const renderer = useRef<ReturnType<typeof import('@/game/battle-board-scene').createBattleBoardScene> | null>(null);
  const [ready, setReady] = useState(false), [error, setError] = useState(''), [draft, setDraft] = useState(layout), [rangeDraft, setRangeDraft] = useState(range), [showRange, setShowRange] = useState(true);
  const [assignments, setAssignments] = useState<DraftAssignment[]>([]), [applied, setApplied] = useState<BattleBoardAssignment[]>([]);
  const [battle, setBattle] = useState<SandboxBattle | null>(null), [running, setRunning] = useState(false);
  const [editingSlotId, setEditingSlotId] = useState<string | null>(null);
  const slots = useMemo(() => createHexGridSlots({ columns: draft.columns, hexGap: draft.hexGap * .22, bands: [{ id: 'enemy', rows: draft.rowsPerTeam }, { id: 'neutral', rows: Math.round(draft.teamGap) }, { id: 'player', rows: draft.rowsPerTeam }] }), [draft]);
  const teamSlots = slots.filter(slot => slot.band === 'player'), enemySlots = slots.filter(slot => slot.band === 'enemy');
  const editingSlot = slots.find(slot => slot.id === editingSlotId);
  useEffect(() => { const previous = document.activeElement as HTMLElement | null; dialog.current?.showModal(); return () => previous?.focus(); }, []);
  useEffect(() => { let disposed = false; import('@/game/battle-board-scene').then(({ createBattleBoardScene }) => { if (!disposed && canvas.current) renderer.current = createBattleBoardScene(canvas.current, layout, () => !disposed && setReady(true)); }).catch(reason => setError(`The battle board could not be prepared: ${reason instanceof Error ? reason.message : 'unknown error'}`)); return () => { disposed = true; renderer.current?.dispose(); renderer.current = null; }; }, []);
  useEffect(() => { renderer.current?.update(draft, applied, rangeDraft, showRange); }, [draft, applied, rangeDraft, showRange]);
  useEffect(() => { if (!running) return; const timer = window.setInterval(() => setBattle(current => current ? stepSandboxBattle(current, rangeDraft) : current), SANDBOX_BATTLE_STEP * 1000); return () => window.clearInterval(timer); }, [running, rangeDraft]);
  useEffect(() => { if (battle) renderer.current?.updateUnitPositions(battle.units); }, [battle]);
  useEffect(() => { setAssignments(current => current.filter(item => slots.some(slot => slot.id === item.slotId && slot.band === item.side))); setApplied([]); setBattle(null); setRunning(false); }, [slots]);
  function assign(slotId: string, side: 'player' | 'enemy', value: string) { setAssignments(current => { const rest = current.filter(item => item.slotId !== slotId); if (!value) return rest; return value === 'chimera-pack' ? [...rest, { slotId, side, mob: 'chimera-pack' }] : [...rest.filter(item => item.axieId !== value), { slotId, side, axieId: value }]; }); }
  function applyFormation() {
    const next: BattleBoardAssignment[] = [];
    for (const item of assignments) {
      if (item.axieId) { const axie = activeAxies.find(candidate => candidate.id === item.axieId); if (axie) next.push({ slotId: item.slotId, side: item.side, name: axie.name, axie }); }
      else if (item.mob) next.push({ slotId: item.slotId, side: 'enemy', name: 'Chimera pack', mob: item.mob });
    }
    setApplied(next); renderer.current?.update(draft, next, rangeDraft, showRange);
    setBattle(null); setRunning(false);
  }
  function clearFormation() {
    setAssignments([]);
    setApplied([]);
    renderer.current?.update(draft, [], rangeDraft, showRange);
    setBattle(null); setRunning(false);
  }
  const selected = (slotId: string) => assignments.find(item => item.slotId === slotId);
  const label = (slotId: string) => { const item = selected(slotId); return item?.axieId ? activeAxies.find(axie => axie.id === item.axieId)?.name ?? 'Axie' : item?.mob ? 'Chimera pack' : 'Assign unit'; };
  const setNumber = (key: keyof typeof draft, minimum: number, maximum: number, integer = false) => (value: number) => setDraft({ ...draft, [key]: Math.max(minimum, Math.min(maximum, integer ? Math.round(value || minimum) : value || minimum)) });
  const setRangeNumber = (key: keyof BattleRangeSettings, minimum: number, maximum: number) => (value: number) => setRangeDraft({ ...rangeDraft, [key]: Math.max(minimum, Math.min(maximum, value || minimum)) });
  function startBattle() {
    const positions = applied.map(assignment => {
      const slot = slots.find(candidate => candidate.id === assignment.slotId)!;
      const stats = assignment.axie ? SANDBOX_AXIE_STATS : SANDBOX_CHIMERA_STATS;
      return { id: assignment.slotId, side: assignment.side, x: slot.x, z: slot.z, facing: assignment.side === 'player' ? Math.PI : 0, attackRange: rangeDraft.meleeAttackRange, ...stats };
    });
    setBattle(createSandboxBattle(positions)); setRunning(true);
  }
  return <dialog ref={dialog} className="battle-dialog battle-sandbox-dialog" aria-label="Battle board sandbox" onCancel={event => { event.preventDefault(); onClose(); }}>
    <header className="battle-header"><div><span className="eyebrow">DEVELOPER · BATTLE SANDBOX</span><h2>Hex board prototype</h2><span>{applied.length ? `${applied.length} assigned model${applied.length === 1 ? '' : 's'} on board` : 'Assign a formation, then apply it to preview models.'}</span></div><button className="secondary" onClick={onClose}>Close sandbox</button></header>
    <div className="battle-field battle-board-field">{!ready && !error && <p className="battle-loading" role="status">Preparing hex board...</p>}{error && <p className="battle-loading" role="alert">{error}</p>}<canvas ref={canvas} aria-label="Hex battle board. Drag to pan and pinch or scroll to zoom." /><span className="battle-side-label enemy">Enemy</span><span className="battle-side-label player">Your team</span><div className="battle-camera"><button aria-label="Zoom battlefield in" onClick={() => renderer.current?.zoom(.85)}>+</button><button aria-label="Zoom battlefield out" onClick={() => renderer.current?.zoom(1.18)}>−</button><button onClick={() => renderer.current?.home()}>Center</button></div></div>
    <div className="battle-controls"><button className="primary" disabled={!applied.some(unit => unit.side === 'player') || !applied.some(unit => unit.side === 'enemy')} onClick={startBattle}>Start battle</button>{battle && <><button className="secondary" onClick={() => setRunning(value => !value)}>{running ? 'Pause' : 'Resume'}</button><button className="secondary" onClick={() => { setBattle(null); setRunning(false); renderer.current?.update(draft, applied, rangeDraft, showRange); }}>Reset positions</button><p role="status">{running ? 'Approach simulation running' : 'Approach simulation paused'} · {(battle.tick / 10).toFixed(1)}s · {battle.units.filter(unit => unit.state === 'marching').length} marching · {battle.units.filter(unit => unit.state === 'approaching').length} walking · {battle.units.filter(unit => unit.state === 'charging').length} rushing · {battle.units.filter(unit => unit.state === 'in-range').length} attack-ready. Default Axie/Chimera speed: {SANDBOX_AXIE_STATS.speed}/{SANDBOX_CHIMERA_STATS.speed}; melee/ranged attack range: {rangeDraft.meleeAttackRange}/{rangeDraft.rangedAttackRange}. Attacks are disabled.</p></>}</div>
    <div className="battle-controls battle-board-controls"><label>Columns per team<input type="number" min={2} max={16} value={draft.columns} onChange={event => setNumber('columns', 2, 16, true)(Number(event.target.value))} /></label><label>Rows per team<input type="number" min={1} max={12} value={draft.rowsPerTeam} onChange={event => setNumber('rowsPerTeam', 1, 12, true)(Number(event.target.value))} /></label><label>Gap between hexes<input type="number" min={0} max={3} step={.05} value={draft.hexGap} onChange={event => setNumber('hexGap', 0, 3)(Number(event.target.value))} /></label><label>Neutral hex rows<input type="number" min={0} max={4} value={draft.teamGap} onChange={event => setNumber('teamGap', 0, 4, true)(Number(event.target.value))} /></label><button className="secondary" onClick={() => onSaveLayout(draft)}>Save layout</button></div>
    <fieldset className="battle-controls battle-board-controls" aria-label="Directional range tuning"><legend>Directional range · JSON configurable</legend><label>Level 0 range<input type="number" min={.1} max={30} step={.1} value={rangeDraft.level0Range} onChange={event => setRangeNumber('level0Range', .1, 30)(Number(event.target.value))} /></label><label>Level 0 angle<input type="number" min={1} max={360} value={rangeDraft.level0Angle} onChange={event => setRangeNumber('level0Angle', 1, 360)(Number(event.target.value))} /></label><label>Body radius<input type="number" min={.1} max={5} step={.1} value={rangeDraft.bodyRadius} onChange={event => setRangeNumber('bodyRadius', .1, 5)(Number(event.target.value))} /></label><label>Level 1 detect range<input type="number" min={.1} max={100} step={.1} value={rangeDraft.level1DetectionRange} onChange={event => setRangeNumber('level1DetectionRange', .1, 100)(Number(event.target.value))} /></label><label>Level 1 angle<input type="number" min={1} max={360} value={rangeDraft.level1DetectionAngle} onChange={event => setRangeNumber('level1DetectionAngle', 1, 360)(Number(event.target.value))} /></label><label>Dash multiplier<input type="number" min={1} max={5} step={.1} value={rangeDraft.dashSpeedMultiplier} onChange={event => setRangeNumber('dashSpeedMultiplier', 1, 5)(Number(event.target.value))} /></label><label><input type="checkbox" checked={showRange} onChange={event => setShowRange(event.target.checked)} /> Show range</label><button className="secondary" onClick={() => onSaveRange(rangeDraft)}>Save range</button></fieldset>
    <fieldset className="battle-controls battle-board-controls" aria-label="Base attack range tuning"><legend>Base attack range · JSON configurable</legend><label>Melee range<input type="number" min={.1} max={30} step={.1} value={rangeDraft.meleeAttackRange} onChange={event => setRangeNumber('meleeAttackRange', .1, 30)(Number(event.target.value))} /></label><label>Ranged range<input type="number" min={.1} max={30} step={.1} value={rangeDraft.rangedAttackRange} onChange={event => setRangeNumber('rangedAttackRange', .1, 30)(Number(event.target.value))} /></label><small>Show range draws melee in cyan and ranged in violet. Current Axies and Chimera packs use the melee value.</small><button className="secondary" onClick={() => onSaveRange(rangeDraft)}>Save attack ranges</button></fieldset>
    <section className="sandbox-formation" aria-label="Sandbox hex assignments"><div><h3>Your team</h3><p>Tap a hex to assign one active Axie. The formation resizes with the board settings.</p><div className="formation-board shared-team-board sandbox-hex-board" style={{ '--formation-columns': draft.columns } as React.CSSProperties}>{Array.from({ length: draft.rowsPerTeam }, (_, row) => <div className={`formation-row ${row % 2 ? 'hex-row-shifted' : ''}`} key={row}>{teamSlots.filter(slot => slot.row === row + draft.rowsPerTeam + Math.round(draft.teamGap)).map(slot => <button className={`formation-slot ${selected(slot.id) ? 'filled' : ''}`} key={slot.id} onClick={() => setEditingSlotId(slot.id)}><strong>{label(slot.id)}</strong><small>Hex {row + 1}-{slot.column + 1}</small></button>)}</div>)}</div></div><div><h3>Enemy</h3><p>Tap a hex to assign an active Axie or Chimera pack.</p><div className="formation-board shared-team-board sandbox-hex-board" style={{ '--formation-columns': draft.columns } as React.CSSProperties}>{Array.from({ length: draft.rowsPerTeam }, (_, row) => <div className={`formation-row ${row % 2 ? 'hex-row-shifted' : ''}`} key={row}>{enemySlots.filter(slot => slot.row === row).map(slot => <button className={`formation-slot ${selected(slot.id) ? 'filled' : ''}`} key={slot.id} onClick={() => setEditingSlotId(slot.id)}><strong>{label(slot.id)}</strong><small>Hex {row + 1}-{slot.column + 1}</small></button>)}</div>)}</div></div></section>
    {editingSlot && <div className="assignment-backdrop" role="presentation" onClick={() => setEditingSlotId(null)}><section className="assignment-popup" role="dialog" aria-modal="true" aria-label="Assign sandbox hex" onClick={event => event.stopPropagation()}><div className="catalog-heading"><div><span className="eyebrow">SANDBOX HEX</span><h3>Assign {editingSlot.band === 'player' ? 'team' : 'enemy'} unit</h3><small>Hex {editingSlot.column + 1} · {editingSlot.band === 'player' ? 'Your team' : 'Enemy'}</small></div><button className="close" onClick={() => setEditingSlotId(null)} aria-label="Close assignment">×</button></div><div className="assignment-list">{activeAxies.map(axie => { const occupied = assignments.some(item => item.slotId !== editingSlot.id && item.axieId === axie.id); const assigned = selected(editingSlot.id)?.axieId === axie.id; return <button key={axie.id} className={`assignment-row ${assigned ? 'assigned' : ''} ${occupied ? 'unavailable' : ''}`} disabled={occupied} onClick={() => { assign(editingSlot.id, editingSlot.band as 'player' | 'enemy', assigned ? '' : axie.id); setEditingSlotId(null); }}><span className="assignment-copy"><strong>{axie.name}</strong><small>{axie.class} · Active Axie</small></span><span className="assignment-action">{assigned ? 'Unassign' : 'Assign'}</span></button>; })}{editingSlot.band === 'enemy' && <button className={`assignment-row ${selected(editingSlot.id)?.mob ? 'assigned' : ''}`} onClick={() => { assign(editingSlot.id, 'enemy', selected(editingSlot.id)?.mob ? '' : 'chimera-pack'); setEditingSlotId(null); }}><span className="assignment-copy"><strong>Chimera pack</strong><small>Available developer mob</small></span><span className="assignment-action">{selected(editingSlot.id)?.mob ? 'Unassign' : 'Assign'}</span></button>}{!activeAxies.length && editingSlot.band === 'player' && <p>No active Axies are available. Deploy Axies in Town first.</p>}</div><div className="placement-actions"><button className="secondary" onClick={() => { assign(editingSlot.id, editingSlot.band as 'player' | 'enemy', ''); setEditingSlotId(null); }}>Clear hex</button><button className="primary" onClick={() => setEditingSlotId(null)}>Done</button></div></section></div>}
    <div className="battle-controls"><button className="primary" onClick={applyFormation}>Apply formation</button><p>Both teams use <strong>{draft.columns} × {draft.rowsPerTeam}</strong> slots. Apply puts the selected Axie and Chimera 3D models on their assigned hexes; it does not start combat or change real formations.</p></div>
    <div className="battle-controls"><button className="secondary" disabled={!assignments.length && !applied.length} onClick={clearFormation}>Clear all units</button></div>
  </dialog>;
}
