const fs = require('node:fs');
const path = require('node:path');
const ts = require('typescript');
const assert = require('node:assert/strict');
const cache = new Map();
function load(file) {
  file = path.resolve(file);
  if (file.endsWith('.json')) return JSON.parse(fs.readFileSync(file, 'utf8'));
  if (cache.has(file)) return cache.get(file).exports;
  const module = { exports: {} };
  cache.set(file, module);
  const source = ts.transpileModule(fs.readFileSync(file, 'utf8'), { compilerOptions: { module: ts.ModuleKind.CommonJS, target: ts.ScriptTarget.ES2020, esModuleInterop: true } }).outputText;
  new Function('require', 'module', 'exports', source)(name => load(path.resolve(path.dirname(file), name.endsWith('.json') ? name : `${name}.ts`)), module, module.exports);
  return module.exports;
}


const b = load('src/game/battle.ts');
const range = load('src/game/battle-range.ts');
const sandboxRules = load('src/game/sandbox-battle.ts');
const save = load('src/game/battle-save.ts');
const u = load('src/game/units.ts');
const f = load('src/game/offense-formations.ts');
const military = load('src/game/military-service.ts');
const world = load('src/game/world.ts');
const replayRules = load('src/game/battle-replay.ts');
const { STARTER_HEROES } = load('src/game/heroes.ts');
const troops = { infantry: 100, archer: 100, scout: 0 };
const army = b.createSandboxArmy('balanced');
assert.equal(army.leaderId, STARTER_HEROES[0].id);
let initial = b.createBattle(army);
const openingPlayer = b.formationCenter(initial, 'player');
const openingEnemy = b.formationCenter(initial, 'enemy');
assert.equal(openingPlayer.x, 0, 'player formation opens centered on the battle axis');
assert.equal(openingEnemy.x, 0, 'enemy formation opens centered on the battle axis');
assert.equal(openingEnemy.z - openingPlayer.z, 18, 'opening teams honor the shared configurable separation');
assert.ok(initial.fighters.filter(fighter => fighter.side === 'player').every(fighter => fighter.facing === 0), 'player opens south-facing north');
assert.ok(initial.fighters.filter(fighter => fighter.side === 'enemy').every(fighter => fighter.facing === Math.PI), 'enemy opens north-facing south');
const recording = replayRules.beginReplay(initial);
const staged = replayRules.replayPresentationBattle(recording, initial);
const stagedPlayer = b.formationCenter(staged, 'player'), stagedEnemy = b.formationCenter(staged, 'enemy');
assert.ok(Math.abs(stagedPlayer.x) < 1e-9 && Math.abs(stagedEnemy.x) < 1e-9, 'replay formations align on the north-south axis');
assert.ok(stagedPlayer.z < 0 && stagedEnemy.z > 0, 'replay stages player south and enemy north');
assert.ok(staged.fighters.every(fighter => fighter.facing === (fighter.side === 'player' ? 0 : Math.PI)), 'opening replay formations face each other');
const advanced = { ...initial, fighters: initial.fighters.map(fighter => fighter.side === 'player' ? { ...fighter, z: fighter.z + 1 } : fighter) };
const stagedAdvanced = replayRules.replayPresentationBattle(recording, advanced);
assert.notEqual(stagedAdvanced.fighters[0].z, staged.fighters[0].z, 'fixed replay transform preserves recorded movement');
assert.equal(initial.fighters.find(f => f.troopKind === 'infantry').maxHp, 2000);
assert.equal(b.damageAfterDefense(100, 100), 50);
const squad = initial.fighters.find(f => f.troopKind === 'infantry');
assert.equal(b.livingCount({ ...squad, hp: 1450 }), 15);
assert.equal(b.livingCount({ ...squad, hp: 0 }), 0);
const before = JSON.stringify(initial);
b.stepBattle(initial);
assert.equal(JSON.stringify(initial), before, 'simulation does not mutate inputs');
function run(battle) { while (!battle.result) battle = b.stepBattle(battle); return battle; }
assert.deepEqual(run(initial), run(structuredClone(initial)), 'deterministic outcomes');
for (const kind of ['balanced', 'infantry', 'archer']) {
  const result = run(b.createBattle(b.createSandboxArmy(kind)));
  assert.ok(['victory', 'defeat'].includes(result.result), `${kind} resolves without deadlock`);
  assert.ok(result.fighters.every(f => f.hp >= 0));
  console.log(`${kind}: ${result.result} in ${result.tick / 10}s`);
}
let melee = { ...initial.fighters[0], stats: { ...squad.stats }, x: 0, z: 0, initialCount: 1, hp: 100, maxHp: 100, targetId: null, cooldown: 0 };
let enemy = { ...melee, id: 'enemy:test', side: 'enemy', x: 0, z: 5 };
let duel = { ...initial, fighters: [melee, enemy], leaderId: null };
let step = b.stepBattle(duel);
assert.equal(step.fighters[0].state, 'charging');
assert.ok(Math.abs(step.fighters[0].z - melee.stats.speed * 1.1 * b.BATTLE_STEP) < 1e-10, '10 percent movement charge');
const archer = { ...melee, stats: { ...b.TROOP_COMBAT_STATS.archer }, troopKind: 'archer' };
step = b.stepBattle({ ...duel, fighters: [archer, enemy] });
assert.equal(step.fighters[0].state, 'attacking');
assert.equal(step.fighters[0].z, 0, 'archers hold shooting distance');
assert.ok(step.fighters[1].hp < enemy.hp);
step = b.stepBattle({ ...duel, fighters: [melee, { ...enemy, z: 50 }] });
assert.equal(step.fighters[0].state, 'holding', 'awareness does not reach distant enemies');
// Level 1 is directional: a unit first needs to be facing its detected enemy.
const watch = b.stepBattle({ ...duel, fighters: [melee, { ...enemy, z: 14 }] });
assert.equal(watch.fighters[1].state, 'holding');
assert.equal(watch.fighters[1].z, 14);
assert.equal(watch.fighters[1].facing, 0);
assert.ok(watch.fighters[0].z > 0, 'ordered attacker continues its approach');
const facedDefender = { ...enemy, facing: Math.PI };
assert.equal(b.stepBattle({ ...duel, fighters: [melee, facedDefender] }).fighters[1].state, 'charging', 'Level 1 dash begins when the defender detects an enemy ahead');
assert.equal(range.level0CanAttack({ x: 0, z: 0, facing: 0 }, { x: 0, z: 4, radius: .5 }, 4, { ...range.DEFAULT_BATTLE_RANGE, level0Angle: 90 }), true, 'Level 0 accepts targets within its facing cone');
assert.equal(range.level0CanAttack({ x: 0, z: 0, facing: 0 }, { x: 4, z: 0, radius: .5 }, 4, { ...range.DEFAULT_BATTLE_RANGE, level0Angle: 90 }), false, 'Level 0 rejects targets outside its facing cone');
const sandboxSettings = { ...range.DEFAULT_BATTLE_RANGE, level0Range: 1, level0Angle: 180, level1DetectionRange: 10, level1DetectionAngle: 180, bodyRadius: .5, dashSpeedMultiplier: 2 };
const sandboxOpening = sandboxRules.createSandboxBattle([{ id: 'player', side: 'player', x: 0, z: 0, facing: 0, speed: 2, attackRange: 1 }, { id: 'enemy', side: 'enemy', x: 0, z: 5, facing: Math.PI, speed: 2, attackRange: 1 }]);
const sandboxStep = sandboxRules.stepSandboxBattle(sandboxOpening, sandboxSettings);
assert.equal(sandboxStep.units[0].state, 'approaching', 'sandbox Level 0 detection starts a walking approach');
assert.ok(sandboxStep.units[0].z > 0, 'sandbox approach moves toward the detected target');
assert.equal(sandboxStep.units[0].hp, undefined, 'sandbox approach state has no health or attack resolution');
const sandboxArrival = sandboxRules.stepSandboxBattle(sandboxRules.createSandboxBattle([{ id: 'player', side: 'player', x: 0, z: 0, facing: 0, speed: 2, attackRange: 1 }, { id: 'enemy', side: 'enemy', x: 0, z: 1, facing: Math.PI, speed: 2, attackRange: 1 }]), sandboxSettings);
assert.equal(sandboxArrival.units[0].state, 'in-range', 'sandbox unit attack range stops an acquired unit without attacking');
const hurt = b.stepBattle({ ...duel, fighters: [melee, { ...enemy, z: 14, hp: 90 }] });
assert.equal(hurt.fighters[1].state, 'approaching', 'damage provokes retaliation beyond Level 1');
assert.ok(hurt.fighters[1].z < 14);
const distantHit = b.stepBattle({ ...duel, fighters: [melee, { ...enemy, z: 20, hp: 90 }] });
assert.equal(distantHit.fighters[1].state, 'approaching', 'damage wakes defenders beyond awareness');
const leashed = b.stepBattle({ ...duel, fighters: [{ ...melee, z: -40 }, { ...enemy, hp: 90 }] });
assert.equal(leashed.fighters[1].state, 'holding', 'retaliation respects camp leash');
const rangedDefender = { ...enemy, stats: { ...b.TROOP_COMBAT_STATS.archer }, troopKind: 'archer', hp: 90, facing: Math.PI };
const rangedStep = b.stepBattle({ ...duel, fighters: [melee, rangedDefender] });
assert.equal(rangedStep.fighters[1].state, 'attacking');
assert.equal(rangedStep.fighters[1].z, rangedDefender.z, 'defender archers stop at bow range');
const lethal = { ...melee, hp: 1, stats: { ...melee.stats, attack: 1000, range: 2 } };
step = b.stepBattle({ ...duel, fighters: [lethal, { ...lethal, side: 'enemy', id: 'enemy:test', z: 1, facing: Math.PI }] });
assert.equal(step.result, 'draw', 'simultaneous lethal attacks have no ordering advantage');
assert.equal(run({ ...initial, retreating: true }).result, 'retreated');
assert.equal(b.stepBattle({ ...duel, tick: b.MAX_BATTLE_TICKS - 1, fighters: [melee, { ...enemy, z: 50 }] }).result, 'draw');
let skillBattle = { ...initial, fighters: initial.fighters.map(f => ({ ...f, x: f.side === 'player' ? 0 : 1, z: 0, hp: f.hp / 2 })) };
const cast = b.activateCommanderSkill(skillBattle);
assert.notEqual(cast, skillBattle);
assert.ok(cast.skillCooldown > 0);
assert.equal(b.activateCommanderSkill(cast), cast, 'cooldown prevents repeated skill casts');
assert.equal(b.activateCommanderSkill({ ...skillBattle, retreating: true }).skillCooldown, 0);
const healer = STARTER_HEROES.find(h => h.parts.mouth === 'Axie Kiss');
assert.ok(healer);
let healing = structuredClone(initial);
const leaderIndex = healing.fighters.findIndex(f => f.id === healing.leaderId);
healing.fighters[leaderIndex].heroId = healer.id;
healing.fighters.forEach(f => { f.x = 0; f.z = 0; });
const woundedIndex = healing.fighters.findIndex(f => f.side === 'player' && f.troopKind === 'infantry');
healing.fighters[woundedIndex].hp = 1450;
const healed = b.activateCommanderSkill(healing);
assert.equal(b.livingCount(healed.fighters[woundedIndex]), 15, 'healing cannot resurrect lost soldiers');
assert.equal(healed.fighters[woundedIndex].hp, 1500, 'healing repairs the remaining wounded soldier');
const retarget = b.stepBattle({ ...duel, fighters: [{ ...melee, targetId: 'dead' }, { ...enemy, id: 'dead', hp: 0 }, { ...enemy, id: 'alive' }] });
assert.equal(retarget.fighters[0].targetId, 'alive');
const target = { id: 'test-garrison', kind: 'garrison', state: 'defended', x: 40, z: 0, loot: { apple: 1 } };
const attacking = { ...army, position: { x: 40, z: 0 }, activity: { action: 'attack', targetId: target.id, targetLabel: 'Garrison' } };
let session = save.createBattleSession(attacking, target);
for (let i = 0; i < 100; i++) session = { ...session, battle: b.stepBattle(session.battle) };
const restored = save.restoreBattleSave(JSON.stringify({ active: session, report: null }), troops).active;
assert.ok(restored, 'valid active battle restores');
assert.equal(JSON.stringify(run(restored.battle)), JSON.stringify(run(session.battle)), 'reload resumes exactly the same simulation');
const legacyOffset = 16 - Math.hypot(target.x - attacking.position.x, target.z - attacking.position.z);
const legacySession = { ...session, battle: { ...session.battle, layoutVersion: undefined, fighters: session.battle.fighters.map(fighter => fighter.side === 'player' ? { ...fighter, z: fighter.z + legacyOffset } : fighter) } };
const migrated = save.restoreBattleSave(JSON.stringify({ active: legacySession, report: null }), troops).active;
assert.ok(migrated, 'legacy active battle restores');
assert.ok(migrated.battle.fighters.every((fighter, index) => Math.hypot(fighter.x - session.battle.fighters[index].x, fighter.z - session.battle.fighters[index].z) < 1e-9), 'legacy active battle keeps its current combat positions after recentering');
for (const corrupt of [null, {}, { ...session.battle, tick: -1 }, { ...session.battle, fighters: [{ ...session.battle.fighters[0], hp: -1 }] }]) {
  assert.equal(save.restoreBattleSave(JSON.stringify({ active: { ...session, battle: corrupt } }), troops).active, null);
}
const completed = { ...session, battle: run(session.battle) };
const formation = f.createEmptyFormation();
formation.assignments.push({ row: 0, column: 1, heroId: STARTER_HEROES[0].id, military: null, militaryCount: 0 }); formation.leader = STARTER_HEROES[0].id;
formation.assignments.push({ row: 0, column: 0, heroId: null, military: 'infantry', militaryCount: 20 });
formation.assignments.push({ row: 2, column: 2, heroId: null, military: 'archer', militaryCount: 20 });
function storageFor(failAt = Infinity) {
  const data = new Map([['unrelated', 'keep']]); let writes = 0;
  return { data, getItem: key => data.get(key) ?? null, setItem(key, value) { if (++writes === failAt) throw Error('Interrupted'); data.set(key, value); }, removeItem: key => data.delete(key), get length() { return data.size; }, key: i => [...data.keys()][i] ?? null };
}
const storage = storageFor();
const outcome = save.commitBattleOutcome(storage, completed, [attacking], troops, [formation], [target], 10000);
assert.equal(outcome.troops.infantry, troops.infantry - outcome.report.losses.infantry);
assert.equal(outcome.units[0].status, completed.battle.result === 'victory' ? 'holding' : 'returning');
assert.equal(outcome.units[0].activity, undefined);
assert.equal(storage.getItem(save.BATTLE_TRANSACTION_KEY), null);
assert.ok(u.restoreUnits(JSON.stringify(outcome.units), outcome.troops, 10000).length, 'survivors restore and remain reserved');
assert.equal(save.restoreBattleSave(storage.getItem(save.BATTLE_SAVE_KEY), outcome.troops).active, null);
assert.ok(save.restoreBattleSave(storage.getItem(save.BATTLE_SAVE_KEY), outcome.troops).report);
for (let failAt = 2; failAt <= 6; failAt++) {
  const interrupted = storageFor(failAt);
  assert.throws(() => save.commitBattleOutcome(interrupted, completed, [attacking], troops, [formation], [target], 10000), /Interrupted/);
  assert.ok(interrupted.getItem(save.BATTLE_TRANSACTION_KEY));
  save.recoverBattleTransaction(interrupted);
  assert.deepEqual([...interrupted.data].sort(), [...storage.data].sort(), `recovery after write ${failAt}`);
  save.recoverBattleTransaction(interrupted);
  assert.equal(interrupted.getItem('unrelated'), 'keep');
}
const win = { ...session, battle: { ...session.battle, result: 'victory', fighters: session.battle.fighters.map(f => f.side === 'enemy' ? { ...f, hp: 0, state: 'defeated', targetId: null } : f) } };
const won = save.commitBattleOutcome(storageFor(), win, [attacking], troops, [formation], [target], 10000);
assert.equal(won.units[0].id, attacking.id);
assert.equal(won.units[0].status, 'holding', 'victorious formation stays deployed');
assert.equal(won.units[0].order, null);
assert.equal(won.units[0].activity, undefined, 'finished attack cannot restart');
assert.equal(u.commandUnit(won.units[0], 'move', 10001, { x: 55, z: 25 }).status, 'moving', 'survivors accept the next order');
assert.equal(u.restoreUnits(JSON.stringify(won.units), won.troops, 10001)[0].status, 'holding', 'victorious survivors remain commandable after reload');
const projection = load('src/game/battle-world.ts');
for (const point of [{ x: 24, z: 0 }, { x: 40, z: -16 }, { x: 40, z: 0 }, { x: 45, z: 5 }]) {
  const march = { ...attacking, position: point };
  const fight = save.createBattleSession(march, target);
  const sessionPlayer = b.formationCenter(fight.battle, 'player');
  const sessionEnemy = b.formationCenter(fight.battle, 'enemy');
  assert.equal(sessionEnemy.z - sessionPlayer.z, 18, 'world sessions retain the centered tactical opening');
  const angle = projection.battleWorldTransform(fight).angle;
  for (const fighter of fight.battle.fighters.filter(f => f.side === 'player')) {
    const member = march.members.find(m => m.id === fighter.memberId);
    const actual = projection.fighterWorldPosition(fight, fighter);
    const expected = { x: point.x + member.offset.x * Math.cos(angle) + member.offset.z * Math.sin(angle), z: point.z - member.offset.x * Math.sin(angle) + member.offset.z * Math.cos(angle) };
    assert.ok(Math.hypot(actual.x - expected.x, actual.z - expected.z) < 1e-9, 'combat begins at the actual formation position');
  }
}
const denied = storageFor(1);
assert.throws(() => save.commitBattleOutcome(denied, completed, [attacking], troops, [formation], [target], 10000), /Interrupted/);
assert.deepEqual([...denied.data], [['unrelated', 'keep']], 'journal failure makes no partial writes');
const malicious = storageFor(); malicious.data.set(save.BATTLE_TRANSACTION_KEY, JSON.stringify([['unrelated', 'bad']]));
assert.throws(() => save.recoverBattleTransaction(malicious), /invalid/);
assert.equal(malicious.getItem('unrelated'), 'keep');
const { resetGame } = load('src/game/reset.ts');
resetGame(storage);
assert.equal(storage.getItem('unrelated'), 'keep');
assert.deepEqual(save.restoreBattleSave(storage.getItem(save.BATTLE_SAVE_KEY), troops), { active: null, report: null });
assert.deepEqual(military.createMilitaryService(storage, army.cityId).getTroops(), { infantry: 0, archer: 0, scout: 0 });
assert.equal(world.restoreWorld(storage.getItem(world.WORLD_SAVE_KEY)), null);
console.log('PASS: battle rules, range, charge, archers, simultaneous damage, retreat, skill cooldown, deterministic resume, casualties, transaction recovery and reset');
