const fs = require('node:fs');
const path = require('node:path');
const ts = require('typescript');
const assert = require('node:assert/strict');
const cache = new Map();
function load(file) {
  file = path.resolve(file);
  if (file.endsWith('.json')) return JSON.parse(fs.readFileSync(file, 'utf8'));
  if (cache.has(file)) return cache.get(file).exports;
  const module = { exports: {} };
  cache.set(file, module);
  const source = ts.transpileModule(fs.readFileSync(file, 'utf8'), { compilerOptions: { module: ts.ModuleKind.CommonJS, target: ts.ScriptTarget.ES2020, esModuleInterop: true } }).outputText;
  new Function('require', 'module', 'exports', source)(name => load(path.resolve(path.dirname(file), name.endsWith('.json') ? name : `${name}.ts`)), module, module.exports);
  return module.exports;
}

const u = load('src/game/units.ts');
const f = load('src/game/offense-formations.ts');
const { STARTER_HEROES } = load('src/game/heroes.ts');
const routes = load('src/game/routes.ts');
const troops = { infantry: 100, archer: 100, scout: 2 };
const formation = f.createEmptyFormation();
formation.front[0].heroId = STARTER_HEROES[0].id;
formation.mid[0] = { heroId: null, military: 'infantry', militaryCount: 80 };
const army = u.createArmy(formation, 0, 'home', 'Home', 10, 'a');
const moving = u.deployUnit(army, [], troops, { x: 100, z: 0 }, 0);
assert.deepEqual(u.unitPosition(moving, 5000), { x: 50, z: 0 });
const redirected = u.commandUnit(moving, 'move', 5000, { x: 50, z: 100 });
assert.equal(redirected.id, moving.id);
assert.deepEqual(redirected.order.origin, { x: 50, z: 0 });
assert.equal(redirected.order.arrivesAt, 15000);
assert.deepEqual(u.unitPosition(redirected, 10000), { x: 50, z: 50 });
const held = u.commandUnit(redirected, 'hold', 10000);
assert.equal(held.order, null);
assert.deepEqual(held.position, { x: 50, z: 50 });
const returned = u.commandUnit(held, 'return', 10000);
assert.deepEqual(returned.order.destination, army.home);
assert.equal(u.settleUnit(returned, returned.order.arrivesAt).status, 'home');
assert.equal(u.settleUnit(moving, 10000).status, 'holding');
assert.throws(() => u.deployUnit({ ...army, id: 'b' }, [moving], troops, { x: 1, z: 1 }, 1), /formation/);
assert.throws(() => u.deployUnit({ ...army, id: 'b', formationIndex: 1 }, [moving], troops, { x: 1, z: 1 }, 1), /Axie/);
const otherFormation = structuredClone(formation);
otherFormation.front[0].heroId = STARTER_HEROES[1].id;
const other = u.createArmy(otherFormation, 1, 'home', 'Home', 10, 'b');
assert.throws(() => u.deployUnit(other, [moving], troops, { x: 1, z: 1 }, 1), /infantry/);
assert.equal(u.deploymentError(army, [returned], troops, returned.order.arrivesAt), null);
assert.deepEqual(u.restoreUnits(JSON.stringify([redirected]), troops, 10000), [redirected]);
assert.deepEqual(u.restoreUnits(JSON.stringify([returned]), troops, returned.order.arrivesAt), []);
for (const bad of ['no json', '{}', '[null]', JSON.stringify([{ ...moving, speed: -1 }]), JSON.stringify([{ ...moving, order: {} }]), JSON.stringify([{ ...moving, members: [{ heroId: 'unknown' }] }])]) assert.deepEqual(u.restoreUnits(bad, troops, 0), []);
assert.equal(u.restoreUnits(JSON.stringify([moving, { ...moving, id: 'duplicate' }]), troops, 0).length, 1);
const scout = u.createScout('home', 'Home', 10, 'scout');
assert.equal(scout.formationIndex, undefined);
const scoutMoving = u.deployUnit(scout, [moving], troops, { x: 30, z: 0 }, 0);
assert.equal(u.settleUnit(scoutMoving, 3000).status, 'holding');
assert.deepEqual(u.restoreUnits(JSON.stringify([scoutMoving]), troops, 1000), [scoutMoving]);
const garrison = { id: 'garrison', kind: 'garrison', x: 80, z: 0, state: 'defended', loot: { apple: 1 } };
const attack = u.commandWorldAction(moving, 'attack', garrison, 5000);
assert.deepEqual(attack.order.destination, { x: garrison.x, z: garrison.z }, 'attack march reaches the world target coordinate');
assert.equal(attack.id, moving.id, 'redirect keeps the deployed formation');
assert.deepEqual(attack.order.origin, { x: 50, z: 0 }, 'redirect starts at the interpolated position');
assert.equal(attack.order.activity.action, 'attack');
assert.equal(u.settleUnit(attack, attack.order.arrivesAt).activity.targetId, garrison.id);
assert.throws(() => u.commandWorldAction(attack, 'occupy', garrison, 5000), /Defeat/);
const defeated = { ...garrison, state: 'defeated' };
assert.equal(u.commandWorldAction(attack, 'occupy', defeated, 5000).order.activity.action, 'occupy');
assert.throws(() => u.commandWorldAction(scoutMoving, 'attack', garrison, 1000), /army formation/);
assert.equal(u.commandWorldAction(scoutMoving, 'scout', garrison, 1000).order.activity.action, 'scout');
const legacy = routes.createOffensiveMarchOrder({ x: 100, z: 0 }, 0, formation, 'Home', 0, 10);
assert.equal(u.migrateMarches(JSON.stringify([legacy, { ...legacy, id: 'duplicate' }]), 'home', troops, 10, 5000).length, 1);
assert.deepEqual(u.unitPosition(u.migrateMarches(JSON.stringify([legacy]), 'home', troops, 10, 5000)[0], 5000), { x: 50, z: 0 });
const { resetGame, RESETTABLE_MODULES } = load('src/game/reset.ts');
assert.ok(RESETTABLE_MODULES.some(m => m.storageKeys.includes(u.UNITS_SAVE_KEY)));
const saved = new Map([[u.UNITS_SAVE_KEY, JSON.stringify([moving])], ['unrelated', 'keep']]);
resetGame({ get length() { return saved.size; }, key: i => [...saved.keys()][i] ?? null, removeItem: key => saved.delete(key) });
assert.equal(saved.get('unrelated'), 'keep');
assert.deepEqual(u.restoreUnits(saved.get(u.UNITS_SAVE_KEY) ?? null, troops, 0), []);
console.log('PASS: unit movement, redirection, world actions, return, reservations, scouts, restoration, migration and reset');
