
/**
 * Generated by Babylon.js Editor
 */

import {
	loadScene,
	scriptsDictionary,
	scriptAssetsCache,
	_applyScriptsForObject,
	_removeRegisteredScriptInstance,
	_preloadScriptsAssets,

	getDefaultRenderingPipeline,
	getSSAO2RenderingPipeline,
	getMotionBlurPostProcess,
	getSSRRenderingPipeline,
	getTAARenderingPipeline,
	getVLSPostProcess,
} from "babylonjs-editor-tools";

// Request all plugins
import "babylonjs-editor-tools/loading/gaussian-splatting";
import "babylonjs-editor-tools/loading/script/preload/plugins/navmesh";

import * as scripts_box from "./scripts/box";

export const scriptsMap = {
    "scripts/box.ts": scripts_box
};

export {
	loadScene,
	scriptsDictionary,
	scriptAssetsCache,
	_applyScriptsForObject,
	_removeRegisteredScriptInstance,
	_preloadScriptsAssets,

	getDefaultRenderingPipeline,
	getSSAO2RenderingPipeline,
	getMotionBlurPostProcess,
	getSSRRenderingPipeline,
	getTAARenderingPipeline,
	getVLSPostProcess,
};
